<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DbContext\DbContext.csproj" />
    <ProjectReference Include="..\DbModels\DbModels.csproj" />
    <ProjectReference Include="..\Configuration\Configuration.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\DbContext\SqlScripts\sqlserver\ClearTravelTestData.sql"
             Link="SqlScripts\sqlserver\ClearTravelTestData.sql"
             CopyToOutputDirectory="PreserveNewest"
             CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
